/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica.Profesor;

import InterfazGrafica.Estudiante.*;
import java.awt.Color;

/**
 *
 * @author krist
 */
public class CalificacionesDocentePanel extends javax.swing.JFrame {

    /**
     * Creates new form HorarioDetalle
     */
    public CalificacionesDocentePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        panelGuardar = new javax.swing.JPanel();
        labelGuardar = new javax.swing.JLabel();
        panelAtras = new javax.swing.JPanel();
        labelAtras = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNota1 = new javax.swing.JTextField();
        textPorcent1 = new javax.swing.JTextField();
        textNota2 = new javax.swing.JTextField();
        textPorcent3 = new javax.swing.JTextField();
        textNota3 = new javax.swing.JTextField();
        textPorcent2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setMaximumSize(new java.awt.Dimension(880, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCedula.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        labelCedula.setText("1000874569");
        jPanel1.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 15, -1, -1));

        labelNombre.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        labelNombre.setText("ALV");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 15, -1, -1));

        panelGuardar.setBackground(new java.awt.Color(145, 179, 59));
        panelGuardar.setPreferredSize(new java.awt.Dimension(212, 55));

        labelGuardar.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        labelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        labelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGuardar.setText("Guardar");
        labelGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelGuardar.setMaximumSize(new java.awt.Dimension(212, 55));
        labelGuardar.setMinimumSize(new java.awt.Dimension(212, 55));
        labelGuardar.setPreferredSize(new java.awt.Dimension(212, 55));
        labelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE)
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.add(panelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 310, 123, 46));

        panelAtras.setBackground(new java.awt.Color(145, 179, 59));
        panelAtras.setPreferredSize(new java.awt.Dimension(212, 55));

        labelAtras.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        labelAtras.setForeground(new java.awt.Color(255, 255, 255));
        labelAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAtras.setText("Atras");
        labelAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAtras.setMaximumSize(new java.awt.Dimension(212, 55));
        labelAtras.setMinimumSize(new java.awt.Dimension(212, 55));
        labelAtras.setPreferredSize(new java.awt.Dimension(212, 55));
        labelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAtrasLayout = new javax.swing.GroupLayout(panelAtras);
        panelAtras.setLayout(panelAtrasLayout);
        panelAtrasLayout.setHorizontalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE)
        );
        panelAtrasLayout.setVerticalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 385, 123, 46));

        jSeparator1.setBackground(new java.awt.Color(186, 186, 186));
        jSeparator1.setForeground(new java.awt.Color(186, 186, 186));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 186, 186)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 47, 826, 2));

        jSeparator2.setBackground(new java.awt.Color(186, 186, 186));
        jSeparator2.setForeground(new java.awt.Color(186, 186, 186));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 186, 186)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 232, 826, 2));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTA 1");
        jLabel1.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 77, 100, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("%");
        jLabel2.setMaximumSize(new java.awt.Dimension(30, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(30, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOTA 2");
        jLabel3.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 77, 100, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("%");
        jLabel4.setMaximumSize(new java.awt.Dimension(30, 40));
        jLabel4.setMinimumSize(new java.awt.Dimension(30, 40));
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 77, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NOTA 3");
        jLabel5.setPreferredSize(new java.awt.Dimension(76, 40));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 77, 100, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("%");
        jLabel6.setMaximumSize(new java.awt.Dimension(30, 40));
        jLabel6.setMinimumSize(new java.awt.Dimension(30, 40));
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        textNota1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        textNota1.setText("4.5");
        textNota1.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(textNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 129, 76, -1));

        textPorcent1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        textPorcent1.setText("30");
        textPorcent1.setPreferredSize(new java.awt.Dimension(32, 30));
        jPanel1.add(textPorcent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 129, -1, -1));

        textNota2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        textNota2.setText("4.0");
        textNota2.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(textNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 129, 76, -1));

        textPorcent3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        textPorcent3.setText("50");
        textPorcent3.setPreferredSize(new java.awt.Dimension(32, 30));
        jPanel1.add(textPorcent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        textNota3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        textNota3.setText("5.0");
        textNota3.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(textNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 129, 76, -1));

        textPorcent2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        textPorcent2.setText("20");
        textPorcent2.setPreferredSize(new java.awt.Dimension(32, 30));
        jPanel1.add(textPorcent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 129, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAtrasMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_labelAtrasMouseClicked

    private void labelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAtrasMouseEntered
        // TODO add your handling code here:
        panelAtras.setBackground(new Color(175,199,107));
    }//GEN-LAST:event_labelAtrasMouseEntered

    private void labelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAtrasMouseExited
        // TODO add your handling code here:
        panelAtras.setBackground(new Color(145,179,59));        
    }//GEN-LAST:event_labelAtrasMouseExited

    private void labelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelGuardarMouseClicked

    private void labelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseEntered
        // TODO add your handling code here:
        panelGuardar.setBackground(new Color(175,199,107));        
    }//GEN-LAST:event_labelGuardarMouseEntered

    private void labelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarMouseExited
        // TODO add your handling code here:
        panelGuardar.setBackground(new Color(145,179,59));          
    }//GEN-LAST:event_labelGuardarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificacionesDocentePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificacionesDocentePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificacionesDocentePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificacionesDocentePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificacionesDocentePanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAtras;
    public javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelGuardar;
    public javax.swing.JLabel labelNombre;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelGuardar;
    public javax.swing.JTextField textNota1;
    public javax.swing.JTextField textNota2;
    public javax.swing.JTextField textNota3;
    public javax.swing.JTextField textPorcent1;
    public javax.swing.JTextField textPorcent2;
    public javax.swing.JTextField textPorcent3;
    // End of variables declaration//GEN-END:variables
}
