/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Profesor;

import Data.HistoriaAcademica;
import Data.ProgramaEstudiante;
import static InterfazGrafica.Inscripcion.InscripcionCancelacion.nombreBD;
import java.awt.Color;

/**
 *
 * @author krist
 */
public class CalificacionesDocenteDetalle extends javax.swing.JPanel {

    /**
     * Creates new form ListaDeClaseDetalle
     */
    public Color colorViejoLabel;    
    public Color colorViejoPanel;        
    public CalificacionesDocenteDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNota1 = new javax.swing.JLabel();
        labelPorcent1 = new javax.swing.JLabel();
        labelNota2 = new javax.swing.JLabel();
        labelPorcent2 = new javax.swing.JLabel();
        labelNota3 = new javax.swing.JLabel();
        labelPorcent3 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(930, 20));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator1.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 0, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator5.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator5.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 0, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator6.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator6.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 0, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator7.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator7.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 0, -1, -1));

        jSeparator8.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator8.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator8.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 0, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator9.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator9.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 0, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(221, 221, 221));
        jSeparator10.setForeground(new java.awt.Color(221, 221, 221));
        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 221)));
        jSeparator10.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        labelCedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCedula.setPreferredSize(new java.awt.Dimension(145, 17));
        add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setMaximumSize(new java.awt.Dimension(269, 17));
        labelNombre.setMinimumSize(new java.awt.Dimension(269, 17));
        labelNombre.setPreferredSize(new java.awt.Dimension(269, 17));
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 0, -1, -1));

        labelNota1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNota1.setMaximumSize(new java.awt.Dimension(269, 17));
        labelNota1.setMinimumSize(new java.awt.Dimension(269, 17));
        labelNota1.setPreferredSize(new java.awt.Dimension(76, 17));
        add(labelNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        labelPorcent1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPorcent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPorcent1.setMaximumSize(new java.awt.Dimension(269, 17));
        labelPorcent1.setMinimumSize(new java.awt.Dimension(269, 17));
        labelPorcent1.setPreferredSize(new java.awt.Dimension(30, 17));
        add(labelPorcent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 0, -1, -1));

        labelNota2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNota2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNota2.setMaximumSize(new java.awt.Dimension(269, 17));
        labelNota2.setMinimumSize(new java.awt.Dimension(269, 17));
        labelNota2.setPreferredSize(new java.awt.Dimension(76, 17));
        add(labelNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        labelPorcent2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPorcent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPorcent2.setMaximumSize(new java.awt.Dimension(269, 17));
        labelPorcent2.setMinimumSize(new java.awt.Dimension(269, 17));
        labelPorcent2.setPreferredSize(new java.awt.Dimension(30, 17));
        add(labelPorcent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 0, -1, -1));

        labelNota3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNota3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNota3.setMaximumSize(new java.awt.Dimension(269, 17));
        labelNota3.setMinimumSize(new java.awt.Dimension(269, 17));
        labelNota3.setPreferredSize(new java.awt.Dimension(76, 17));
        add(labelNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        labelPorcent3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPorcent3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPorcent3.setMaximumSize(new java.awt.Dimension(269, 17));
        labelPorcent3.setMinimumSize(new java.awt.Dimension(269, 17));
        labelPorcent3.setPreferredSize(new java.awt.Dimension(30, 17));
        add(labelPorcent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        CalificacionesDocentePanel califDocent = new CalificacionesDocentePanel();
        califDocent.setVisible(true);
        //horar.setLocationRelativeTo(null);
        califDocent.setDefaultCloseOperation(califDocent.DISPOSE_ON_CLOSE);

        califDocent.setLocation(400, 175);   
        
            ProgramaEstudiante.mostrarProgramaEstudiante(nombreBD);       
            HistoriaAcademica.mostrarHistoria_Academica("Academico",ProgramaEstudiante.Id_programa);
            
        califDocent.labelNombre.setText(labelNombre.getText());
        califDocent.labelCedula.setText(labelCedula.getText());
        
        califDocent.CtextNota1.setText(labelNota1.getText());
        califDocent.CtextPorcent1.setText(labelPorcent1.getText());    
        
        califDocent.CtextNota2.setText(labelNota2.getText());
        califDocent.CtextPorcent2.setText(labelPorcent2.getText());    

        califDocent.CtextNota3.setText(labelNota3.getText());
        califDocent.CtextPorcent3.setText(labelPorcent3.getText());  
        
        
             
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        colorViejoLabel = labelNombre.getForeground();
        colorViejoPanel = getBackground();
        
        setBackground(new Color(145,179,59));
        
        labelCedula.setForeground(Color.WHITE);

        labelNombre.setForeground(Color.WHITE);

        labelNota1.setForeground(Color.WHITE);
        labelPorcent1.setForeground(Color.WHITE);

        labelNota2.setForeground(Color.WHITE);
        labelPorcent2.setForeground(Color.WHITE);
        
        labelNota3.setForeground(Color.WHITE);
        labelPorcent3.setForeground(Color.WHITE);


      
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        labelNombre.setForeground(colorViejoLabel);
        labelCedula.setForeground(colorViejoLabel);
        
        labelNota1.setForeground(colorViejoLabel);
        labelPorcent1.setForeground(colorViejoLabel);

        labelNota2.setForeground(colorViejoLabel);
        labelPorcent2.setForeground(colorViejoLabel);

        labelNota3.setForeground(colorViejoLabel);
        labelPorcent3.setForeground(colorViejoLabel);        
  
        setBackground(colorViejoPanel);      
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel labelCedula;
    public javax.swing.JLabel labelNombre;
    public javax.swing.JLabel labelNota1;
    public javax.swing.JLabel labelNota2;
    public javax.swing.JLabel labelNota3;
    public javax.swing.JLabel labelPorcent1;
    public javax.swing.JLabel labelPorcent2;
    public javax.swing.JLabel labelPorcent3;
    // End of variables declaration//GEN-END:variables
}
