/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import java.awt.Dimension;

/**
 *
 * @author krist
 */
public class DatosPersonalesGUI extends javax.swing.JPanel {

    /**
     * Creates new form DatosPersonales
     */
    public DatosPersonalesGUI() {

        initComponents();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_Nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_Cedula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_Direccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_Tel_Fijo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_Tel_Movil = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_Correo_Institucional = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_AñoIngreso = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(221, 221, 221));
        setPreferredSize(new java.awt.Dimension(1007, 1000));

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 2000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("DATOS PERSONALES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 720, 100));

        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        label_Nombre.setText("---------------------------");
        jPanel1.add(label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel3.setText("CEDULA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        label_Cedula.setText("-----------------------------");
        jPanel1.add(label_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel4.setText("DIRECCIÓN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        label_Direccion.setText("-----------------------");
        jPanel1.add(label_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 140, -1));

        jLabel5.setText("TELEFONO FIJO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        label_Tel_Fijo.setText("-----------------------");
        jPanel1.add(label_Tel_Fijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabel6.setText("TELEFONO MOVIL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        label_Tel_Movil.setText("------------------------- ");
        jPanel1.add(label_Tel_Movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel7.setText("CORREO INSTITUCIONAL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 750, -1, -1));

        label_Correo_Institucional.setText("---------------------------");
        jPanel1.add(label_Correo_Institucional, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 770, -1, -1));

        jLabel8.setText("AÑO INGRESO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        label_AñoIngreso.setText("--------------------------");
        jPanel1.add(label_AñoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 543, 970, 30));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel label_AñoIngreso;
    public javax.swing.JLabel label_Cedula;
    public javax.swing.JLabel label_Correo_Institucional;
    public javax.swing.JLabel label_Direccion;
    public javax.swing.JLabel label_Nombre;
    public javax.swing.JLabel label_Tel_Fijo;
    public javax.swing.JLabel label_Tel_Movil;
    // End of variables declaration//GEN-END:variables
}
