/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import Data.DatosPersonalesConsulta;
import Data.ModificarDatosPersonales;
import static InterfazGrafica.DatosPersonalesGUI.mostrarPanel;
import static InterfazGrafica.PantallaPrincipal.Content;
import static InterfazGrafica.PantallaPrincipal.mostrarPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author krist
 */
public class ModificarDatosPersonalesGUI extends javax.swing.JPanel {

    /**
     * Creates new form ModificarDatosPersonalesGUI
     */
    public ModificarDatosPersonalesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_Nombre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaTexto_Tel_Fijo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        label_Cedula = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label_Correo_Institucional = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cajaTexto_Tel_Movil = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cajaTexto_Direccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        label_AñoIngreso = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        label_Carrera = new javax.swing.JLabel();
        panel_Guardar = new javax.swing.JPanel();
        label_Guardar = new javax.swing.JLabel();
        panel_Cancelar = new javax.swing.JPanel();
        label_Cancelar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 221));
        setPreferredSize(new java.awt.Dimension(1007, 1000));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 2000));

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 3000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(145, 179, 59));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 335, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Importante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("En está pantalla podrá modificar sus datos personales. Algunos datos no");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 540, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("podrán ser modificados desde está pantalla. Si necesita modificar alguno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 540, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("por favor diríjase a la División de Registro de la Sede o quien haga sus");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 540, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("veces. ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 540, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 970, 10));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel6.setText("Datos básicos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setText("Nombres y apellidos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        label_Nombre.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        label_Nombre.setText("-------------------------------------------");
        jPanel1.add(label_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setText("Teléfono fijo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        cajaTexto_Tel_Fijo.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        cajaTexto_Tel_Fijo.setText("-------------------------------------------");
        cajaTexto_Tel_Fijo.setPreferredSize(new java.awt.Dimension(258, 21));
        jPanel1.add(cajaTexto_Tel_Fijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setText("Cédula");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        label_Cedula.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        label_Cedula.setText("-------------------------------------------");
        jPanel1.add(label_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setText("Correo institucional");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        label_Correo_Institucional.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        label_Correo_Institucional.setText("-------------------------------------------");
        jPanel1.add(label_Correo_Institucional, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setText("Teléfono móvil");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        cajaTexto_Tel_Movil.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        cajaTexto_Tel_Movil.setText("-------------------------------------------");
        cajaTexto_Tel_Movil.setPreferredSize(new java.awt.Dimension(258, 21));
        jPanel1.add(cajaTexto_Tel_Movil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel13.setText("Dirección");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        cajaTexto_Direccion.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        cajaTexto_Direccion.setText("-------------------------------------------");
        cajaTexto_Direccion.setPreferredSize(new java.awt.Dimension(258, 21));
        jPanel1.add(cajaTexto_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel14.setText("Año de ingreso");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        label_AñoIngreso.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        label_AñoIngreso.setText("-------------------------------------------");
        jPanel1.add(label_AñoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel16.setText("Carrera");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, -1));

        label_Carrera.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        label_Carrera.setText("-------------------------------------------");
        jPanel1.add(label_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        panel_Guardar.setBackground(new java.awt.Color(145, 179, 59));
        panel_Guardar.setPreferredSize(new java.awt.Dimension(130, 40));

        label_Guardar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        label_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        label_Guardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Guardar.setText("Guardar");
        label_Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_GuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_GuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_GuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_GuardarLayout = new javax.swing.GroupLayout(panel_Guardar);
        panel_Guardar.setLayout(panel_GuardarLayout);
        panel_GuardarLayout.setHorizontalGroup(
            panel_GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panel_GuardarLayout.setVerticalGroup(
            panel_GuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panel_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        panel_Cancelar.setBackground(new java.awt.Color(145, 179, 59));
        panel_Cancelar.setPreferredSize(new java.awt.Dimension(130, 40));

        label_Cancelar.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        label_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        label_Cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Cancelar.setText("Cancelar");
        label_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_CancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_CancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_CancelarLayout = new javax.swing.GroupLayout(panel_Cancelar);
        panel_Cancelar.setLayout(panel_CancelarLayout);
        panel_CancelarLayout.setHorizontalGroup(
            panel_CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panel_CancelarLayout.setVerticalGroup(
            panel_CancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panel_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void label_GuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_GuardarMouseEntered
        // TODO add your handling code here:
        panel_Guardar.setBackground(new Color(175,199,107));
    }//GEN-LAST:event_label_GuardarMouseEntered

    private void label_GuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_GuardarMouseExited
        // TODO add your handling code here:
        panel_Guardar.setBackground(new Color(145,179,59));
    }//GEN-LAST:event_label_GuardarMouseExited

    private void label_CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CancelarMouseEntered
        // TODO add your handling code here:
        panel_Cancelar.setBackground(new Color(175,199,107));
    }//GEN-LAST:event_label_CancelarMouseEntered

    private void label_CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CancelarMouseExited
        // TODO add your handling code here:
        panel_Cancelar.setBackground(new Color(145,179,59));
    }//GEN-LAST:event_label_CancelarMouseExited

    private void label_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CancelarMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal.mostrarDatos_Personales();
    }//GEN-LAST:event_label_CancelarMouseClicked

    private void label_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_GuardarMouseClicked
        // TODO add your handling code here:
        modificarDatos_Personales();
        PantallaPrincipal.mostrarDatos_Personales();
    }//GEN-LAST:event_label_GuardarMouseClicked

        public static void modificarDatos_Personales(){
        String direccion = cajaTexto_Direccion.getText();
        String tel_fijo = cajaTexto_Tel_Fijo.getText();
        String tel_movil= cajaTexto_Tel_Movil.getText();
        
        ModificarDatosPersonales.modificarDatos_Personales("Academico",direccion,tel_fijo,tel_movil);
            System.out.println(direccion + "" + tel_fijo + " " + tel_movil);
        } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField cajaTexto_Direccion;
    public static javax.swing.JTextField cajaTexto_Tel_Fijo;
    public static javax.swing.JTextField cajaTexto_Tel_Movil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel label_AñoIngreso;
    private javax.swing.JLabel label_Cancelar;
    public javax.swing.JLabel label_Carrera;
    public javax.swing.JLabel label_Cedula;
    public javax.swing.JLabel label_Correo_Institucional;
    private javax.swing.JLabel label_Guardar;
    public javax.swing.JLabel label_Nombre;
    private javax.swing.JPanel panel_Cancelar;
    private javax.swing.JPanel panel_Guardar;
    // End of variables declaration//GEN-END:variables
}
