/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Inscripcion;

import InterfazGrafica.Inscripcion.InscripcionBienvenidaPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author krist
 */
public class InscripcionBienvenida extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenida
     */
    public InscripcionBienvenida() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMensajeBienvenida = new javax.swing.JPanel();

        setBackground(new java.awt.Color(221, 221, 221));
        setPreferredSize(new java.awt.Dimension(1350, 510));

        panelMensajeBienvenida.setPreferredSize(new java.awt.Dimension(1200, 420));
        panelMensajeBienvenida.setLayout(new javax.swing.BoxLayout(panelMensajeBienvenida, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(panelMensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelMensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        public static void agregarPanelBienvenida(JFrame frame) {
        InscripcionBienvenidaPanel panel = new InscripcionBienvenidaPanel();
        panel.setPreferredSize(new Dimension(1200, 420));
        panel.setMaximumSize(new Dimension(1200,420));
        panel.setMinimumSize(new Dimension(1200,420));
        
        //JFrame miFrame = frame;
        panel.Frame = frame;

        panelMensajeBienvenida.add(panel);
        panelMensajeBienvenida.revalidate();
        panelMensajeBienvenida.repaint();
    }   
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel panelMensajeBienvenida;
    // End of variables declaration//GEN-END:variables
}
