/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Estudiante;

import java.awt.Color;

/**
 *
 * @author krist
 */
public class HistoriaAcadAsigPanel extends javax.swing.JPanel {

    /**
     * Creates new form panel
     */
    public Color colorViejo;
    public HistoriaAcadAsigPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMateria = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelCreditos = new javax.swing.JLabel();
        labelPeriodo = new javax.swing.JLabel();
        labelNota = new javax.swing.JLabel();
        labelAPROBADO = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(910, 40));
        setMinimumSize(new java.awt.Dimension(910, 40));
        setPreferredSize(new java.awt.Dimension(910, 40));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMateria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMateria.setText("MATERIA");
        labelMateria.setMaximumSize(new java.awt.Dimension(344, 40));
        labelMateria.setMinimumSize(new java.awt.Dimension(344, 40));
        labelMateria.setPreferredSize(new java.awt.Dimension(344, 40));
        add(labelMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipo.setText("TIPO");
        labelTipo.setMaximumSize(new java.awt.Dimension(185, 40));
        labelTipo.setMinimumSize(new java.awt.Dimension(185, 40));
        labelTipo.setPreferredSize(new java.awt.Dimension(185, 40));
        add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 0, -1, 40));

        labelCreditos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCreditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCreditos.setText("CREDITOS");
        labelCreditos.setMaximumSize(new java.awt.Dimension(81, 40));
        labelCreditos.setMinimumSize(new java.awt.Dimension(81, 40));
        labelCreditos.setPreferredSize(new java.awt.Dimension(81, 40));
        add(labelCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 40));

        labelPeriodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPeriodo.setText("PERIODO");
        labelPeriodo.setMaximumSize(new java.awt.Dimension(125, 40));
        labelPeriodo.setMinimumSize(new java.awt.Dimension(125, 40));
        labelPeriodo.setPreferredSize(new java.awt.Dimension(125, 40));
        add(labelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 0, -1, 40));

        labelNota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNota.setText("5,0");
        labelNota.setMaximumSize(new java.awt.Dimension(150, 26));
        labelNota.setMinimumSize(new java.awt.Dimension(150, 26));
        labelNota.setPreferredSize(new java.awt.Dimension(150, 26));
        add(labelNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, -6, -1, 30));

        labelAPROBADO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelAPROBADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAPROBADO.setText("REPROBADO");
        labelAPROBADO.setMaximumSize(new java.awt.Dimension(150, 26));
        labelAPROBADO.setMinimumSize(new java.awt.Dimension(150, 26));
        labelAPROBADO.setPreferredSize(new java.awt.Dimension(150, 26));
        add(labelAPROBADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 14, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel labelAPROBADO;
    public javax.swing.JLabel labelCreditos;
    public javax.swing.JLabel labelMateria;
    public javax.swing.JLabel labelNota;
    public javax.swing.JLabel labelPeriodo;
    public javax.swing.JLabel labelTipo;
    // End of variables declaration//GEN-END:variables
}
