/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Estudiante;

import Data.HistoriaAcademica;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashSet;

/**
 *
 * @author krist
 */
public class HorarioEstudPanel extends javax.swing.JPanel {

    /**
     * Creates new form HorarioEstudPanel
     */
    
    public static Color colorViejo;       
    public HorarioEstudPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHorario = new javax.swing.JLabel();
        labelMateria = new javax.swing.JLabel();
        labelSalon = new javax.swing.JLabel();
        labelEdificio = new javax.swing.JLabel();
        labelPeriodo = new javax.swing.JLabel();
        labelHoraInicio = new javax.swing.JLabel();
        labelHoraFinal = new javax.swing.JLabel();
        labelSalonNom = new javax.swing.JLabel();
        labelEdifNom = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelActividad = new javax.swing.JLabel();
        labelProfeNom = new javax.swing.JLabel();
        labelMateriaID = new javax.swing.JLabel();
        labelSede = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 221));
        setMaximumSize(new java.awt.Dimension(130, 45));
        setMinimumSize(new java.awt.Dimension(130, 45));
        setPreferredSize(new java.awt.Dimension(130, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHorario.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        labelHorario.setText("7:00 Materia 1 bsfgfhff");
        labelHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelHorario.setMaximumSize(new java.awt.Dimension(130, 45));
        labelHorario.setMinimumSize(new java.awt.Dimension(130, 45));
        labelHorario.setPreferredSize(new java.awt.Dimension(130, 45));
        labelHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHorarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelHorarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelHorarioMouseExited(evt);
            }
        });
        add(labelHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelMateria.setText("Materia");
        add(labelMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        labelSalon.setText("Salon");
        add(labelSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        labelEdificio.setText("Edificio");
        add(labelEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        labelPeriodo.setText("Periodo");
        add(labelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        labelHoraInicio.setText("horaInicio");
        add(labelHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        labelHoraFinal.setText("horaFinal");
        add(labelHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        labelSalonNom.setText("Nomsalon");
        add(labelSalonNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        labelEdifNom.setText("EdifNom");
        add(labelEdifNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        labelGrupo.setText("Grupo");
        add(labelGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        labelActividad.setText("Actividad");
        add(labelActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        labelProfeNom.setText("ProfeNom");
        add(labelProfeNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        labelMateriaID.setText("IdMateria");
        add(labelMateriaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        labelSede.setText("Sede");
        add(labelSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelHorarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHorarioMouseEntered
        // TODO add your handling code here:
        colorViejo = labelHorario.getForeground();
        labelHorario.setBackground(new Color(145,179,59));
        labelHorario.setForeground(new Color(145,179,59));
    }//GEN-LAST:event_labelHorarioMouseEntered

    private void labelHorarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHorarioMouseExited
        // TODO add your handling code here:
        labelHorario.setBackground(colorViejo);
        labelHorario.setForeground(colorViejo);
    }//GEN-LAST:event_labelHorarioMouseExited

    private void labelHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHorarioMouseClicked
        // TODO add your handling code here:
        HorarioDetalle horar = new HorarioDetalle();
        horar.setVisible(true);
        //horar.setLocationRelativeTo(null);
        horar.setDefaultCloseOperation(horar.DISPOSE_ON_CLOSE);

        horar.setLocation(400, 175);   
        
        horar.labelMateriaID.setText(labelMateriaID.getText());
        horar.labelMateria.setText(labelMateria.getText());
        
        horar.labelHoraInicio.setText(labelHoraInicio.getText());
        horar.labelHoraFinal.setText(labelHoraFinal.getText());
        
        horar.labelSalon.setText(labelSalon.getText());
        horar.labelEdificio.setText(labelEdificio.getText());
        horar.labelEdificio1.setText(labelEdificio.getText());
        horar.labelNombreEdif.setText(labelEdifNom.getText());
        horar.labelNombreSal.setText(labelSalonNom.getText());
               
        horar.labelPeriodo.setText(labelPeriodo.getText());
        
        horar.labelActividad.setText(labelActividad.getText());
        horar.labelGrupo.setText(labelGrupo.getText());
        
        horar.labelProfeNom.setText(labelProfeNom.getText());        
        horar.labelSede.setText(labelSede.getText());
        
        HistoriaAcademica.mostrarHistoria_Academica("Academico");
        
        horar.labelCarrera.setText(HistoriaAcademica.Carrera);
        
    }//GEN-LAST:event_labelHorarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel labelActividad;
    public javax.swing.JLabel labelEdifNom;
    public javax.swing.JLabel labelEdificio;
    public javax.swing.JLabel labelGrupo;
    public javax.swing.JLabel labelHoraFinal;
    public javax.swing.JLabel labelHoraInicio;
    public javax.swing.JLabel labelHorario;
    public javax.swing.JLabel labelMateria;
    public javax.swing.JLabel labelMateriaID;
    public javax.swing.JLabel labelPeriodo;
    public javax.swing.JLabel labelProfeNom;
    public javax.swing.JLabel labelSalon;
    public javax.swing.JLabel labelSalonNom;
    public javax.swing.JLabel labelSede;
    // End of variables declaration//GEN-END:variables
}
