/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Estudiante;

import java.awt.Color;

/**
 *
 * @author krist
 */
public class InscripcionCitaVencida extends javax.swing.JPanel {

    /**
     * Creates new form InscripcionProximaCita
     */
    public InscripcionCitaVencida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelCarrera = new javax.swing.JLabel();
        labelIdCarrera = new javax.swing.JLabel();
        labelCarrera1 = new javax.swing.JLabel();
        labelFacultad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelFechaInicial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelFechaFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelHoraInicial = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelHoraFinal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 221));
        setMaximumSize(new java.awt.Dimension(860, 90));
        setMinimumSize(new java.awt.Dimension(860, 90));
        setPreferredSize(new java.awt.Dimension(860, 90));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel1.setText("Información de la cita");

        labelCarrera.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCarrera.setText("INGENIERÍA DE SISTEMAS Y COMPUTACIÓN");

        labelIdCarrera.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelIdCarrera.setText("(81240)");

        labelCarrera1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelCarrera1.setText("FACULTAD DE ");

        labelFacultad.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelFacultad.setText("FACULTAD");

        jPanel1.setBackground(new java.awt.Color(186, 186, 186));
        jPanel1.setPreferredSize(new java.awt.Dimension(251, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        labelFechaInicial.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelFechaInicial.setText("30/05/2023");
        jPanel1.add(labelFechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 0, -1, -1));

        labelFechaFinal.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelFechaFinal.setText("30/05/2023");
        jPanel1.add(labelFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Hora:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 23, -1, -1));

        labelHoraInicial.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelHoraInicial.setText("15:30");
        jPanel1.add(labelHoraInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 23, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 23, -1, -1));

        labelHoraFinal.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelHoraFinal.setText("15:30");
        jPanel1.add(labelHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 23, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCarrera1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFacultad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCarrera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIdCarrera))))
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCarrera)
                            .addComponent(labelIdCarrera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCarrera1)
                            .addComponent(labelFacultad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelCarrera;
    private javax.swing.JLabel labelCarrera1;
    public javax.swing.JLabel labelFacultad;
    public javax.swing.JLabel labelFechaFinal;
    public javax.swing.JLabel labelFechaInicial;
    public javax.swing.JLabel labelHoraFinal;
    public javax.swing.JLabel labelHoraInicial;
    public javax.swing.JLabel labelIdCarrera;
    // End of variables declaration//GEN-END:variables
}
