/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Estudiante;

/**
 *
 * @author krist
 */
public class InscripcionLibreEleccionDetalle extends javax.swing.JPanel {

    /**
     * Creates new form InscripcionAsignaturas
     */
    public InscripcionLibreEleccionDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombreMateria = new javax.swing.JLabel();
        labelMateriaID = new javax.swing.JLabel();
        labelMateriaID2 = new javax.swing.JLabel();
        labelMateriaID3 = new javax.swing.JLabel();
        labelCreditos = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        labelSede = new javax.swing.JLabel();
        labelNombreMateria2 = new javax.swing.JLabel();
        labelNombreMateria3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        setMaximumSize(new java.awt.Dimension(900, 125));
        setMinimumSize(new java.awt.Dimension(900, 125));
        setPreferredSize(new java.awt.Dimension(900, 125));

        jPanel1.setBackground(new java.awt.Color(145, 179, 59));
        jPanel1.setMaximumSize(new java.awt.Dimension(4, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(4, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(4, 121));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        labelNombreMateria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelNombreMateria.setText("Nombre Asignatura");

        labelMateriaID.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelMateriaID.setText("ID Materia");

        labelMateriaID2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMateriaID2.setText("Sin límite de cupos");

        labelMateriaID3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMateriaID3.setText("Créditos");

        labelCreditos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCreditos.setText("6");

        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 221, 211)));
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelSede.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelSede.setText("SEDE");

        labelNombreMateria2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelNombreMateria2.setText("SEDE");

        labelNombreMateria3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        labelNombreMateria3.setText("COMPONENTE DE LIBRE ELECCIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMateriaID2)
                            .addComponent(labelNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombreMateria2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSede)))
                        .addGap(18, 18, 18)
                        .addComponent(labelMateriaID)
                        .addGap(336, 336, 336)
                        .addComponent(labelMateriaID3)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombreMateria3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelCreditos)
                        .addGap(90, 90, 90)))
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelNombreMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreMateria2)
                            .addComponent(labelSede))
                        .addGap(9, 9, 9)
                        .addComponent(labelNombreMateria3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMateriaID2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelMateriaID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelMateriaID3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCreditos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelCreditos;
    public javax.swing.JLabel labelMateriaID;
    private javax.swing.JLabel labelMateriaID2;
    private javax.swing.JLabel labelMateriaID3;
    public javax.swing.JLabel labelNombreMateria;
    public javax.swing.JLabel labelNombreMateria2;
    public javax.swing.JLabel labelNombreMateria3;
    public javax.swing.JLabel labelSede;
    // End of variables declaration//GEN-END:variables
}
