/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica.Estudiante;

import java.awt.Color;
import javax.swing.JFrame;
import InterfazGrafica.Estudiante.InscripcionFrame;
import static InterfazGrafica.Estudiante.InscripcionFrame.mostrar_PlanEstudios_Asignatura;
import javax.swing.SwingUtilities;
/**
 *
 * @author krist
 */
public class InscripcionBienvenidaPanel extends javax.swing.JPanel {

    /**
     * Creates new form InscripcionBienvenidaSinAcceso
     */
    public static JFrame Frame;  
    public InscripcionBienvenidaPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSalir = new javax.swing.JPanel();
        labelContinuar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 221));
        setMaximumSize(new java.awt.Dimension(1200, 420));
        setMinimumSize(new java.awt.Dimension(1200, 420));
        setPreferredSize(new java.awt.Dimension(1200, 420));

        panelSalir.setBackground(new java.awt.Color(145, 179, 59));

        labelContinuar.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        labelContinuar.setForeground(new java.awt.Color(255, 255, 255));
        labelContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelContinuar.setText("CONTINUAR");
        labelContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelContinuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelContinuarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("CARRERA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 15, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Bienvenido al sistema de inscripción de asignaturas de la Universidad Nacional de Colombia");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 59, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 109, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(517, 517, 517))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuarMouseClicked
        // TODO add your handling code here:
        mostrar_PlanEstudios_Asignatura();
        InscripcionFrame.panelBienvenida.setBackground(new Color(186,186,186));
        
    }//GEN-LAST:event_labelContinuarMouseClicked

    private void labelContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuarMouseEntered
        // TODO add your handling code here:
        panelSalir.setBackground(new Color(175,199,107));        
    }//GEN-LAST:event_labelContinuarMouseEntered

    private void labelContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelContinuarMouseExited
        // TODO add your handling code here:
        panelSalir.setBackground(new Color(145,179,59));         
    }//GEN-LAST:event_labelContinuarMouseExited

    public static void metodoStatic(){
        Frame.dispose(); // Cerrar la instancia de InscripcionFrame
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelContinuar;
    private javax.swing.JPanel panelSalir;
    // End of variables declaration//GEN-END:variables
}
