/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica.Estudiante;

import Data.DatosPersonalesEstud;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author krist
 */
public class PantallaPrincipalEstudGUI extends javax.swing.JFrame {


    /**
     * Creates new form DatosEstudiante
     */
    public PantallaPrincipalEstudGUI() {
        
        initComponents();
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Principal = new javax.swing.JPanel();
        Label_Escudo = new javax.swing.JLabel();
        Panel_Superior_Gris = new javax.swing.JPanel();
        Label_Portal_Servicios = new javax.swing.JLabel();
        Panel_Usuario = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        Label_Icono_Usuario = new javax.swing.JLabel();
        Panel_Izquierda_Verde = new javax.swing.JPanel();
        Panel_Datos_Personales = new javax.swing.JPanel();
        label_Datos_Personales = new javax.swing.JLabel();
        Panel_Informacion_Acad = new javax.swing.JPanel();
        Label_Informacion_Acad = new javax.swing.JLabel();
        Panel_Inscripcion = new javax.swing.JPanel();
        labelInscripcion = new javax.swing.JLabel();
        ContentEstud = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_Principal.setBackground(new java.awt.Color(221, 221, 221));
        panel_Principal.setPreferredSize(new java.awt.Dimension(1350, 700));
        panel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Escudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escudoUnal.jpg"))); // NOI18N
        Label_Escudo.setPreferredSize(new java.awt.Dimension(294, 106));
        panel_Principal.add(Label_Escudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, -1));

        Panel_Superior_Gris.setBackground(new java.awt.Color(83, 85, 86));
        Panel_Superior_Gris.setPreferredSize(new java.awt.Dimension(1366, 84));
        Panel_Superior_Gris.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Portal_Servicios.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Label_Portal_Servicios.setForeground(new java.awt.Color(255, 255, 255));
        Label_Portal_Servicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Portal_Servicios.setText("PORTAL DE SERVICIOS ACADÉMICOS");
        Panel_Superior_Gris.add(Label_Portal_Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        Panel_Usuario.setBackground(new java.awt.Color(145, 179, 59));
        Panel_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Usuario.setPreferredSize(new java.awt.Dimension(328, 60));
        Panel_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_UsuarioMouseExited(evt);
            }
        });
        Panel_Usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Usuario.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Label_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Usuario.setText("cbarrerar");
        Panel_Usuario.add(Label_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 60));

        Label_Icono_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoUsuarioPequeño.png"))); // NOI18N
        Label_Icono_Usuario.setText("jLabel8");
        Label_Icono_Usuario.setPreferredSize(new java.awt.Dimension(40, 40));
        Label_Icono_Usuario.setRequestFocusEnabled(false);
        Panel_Usuario.add(Label_Icono_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        Panel_Superior_Gris.add(Panel_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 0, -1, -1));

        panel_Principal.add(Panel_Superior_Gris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_Izquierda_Verde.setBackground(new java.awt.Color(145, 179, 59));
        Panel_Izquierda_Verde.setPreferredSize(new java.awt.Dimension(343, 700));
        Panel_Izquierda_Verde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Datos_Personales.setBackground(new java.awt.Color(145, 179, 59));
        Panel_Datos_Personales.setPreferredSize(new java.awt.Dimension(343, 81));
        Panel_Datos_Personales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Datos_Personales.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label_Datos_Personales.setForeground(new java.awt.Color(255, 255, 255));
        label_Datos_Personales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Datos_Personales.setText("DATOS PERSONALES");
        label_Datos_Personales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_Datos_Personales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_Datos_PersonalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_Datos_PersonalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_Datos_PersonalesMouseExited(evt);
            }
        });
        Panel_Datos_Personales.add(label_Datos_Personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 80));

        Panel_Izquierda_Verde.add(Panel_Datos_Personales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, -1, -1));

        Panel_Informacion_Acad.setBackground(new java.awt.Color(145, 179, 59));
        Panel_Informacion_Acad.setPreferredSize(new java.awt.Dimension(343, 81));
        Panel_Informacion_Acad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Informacion_Acad.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Label_Informacion_Acad.setForeground(new java.awt.Color(255, 255, 255));
        Label_Informacion_Acad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Informacion_Acad.setText("INFORMACIÓN ACADÉMICA");
        Label_Informacion_Acad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_Informacion_Acad.setPreferredSize(new java.awt.Dimension(200, 26));
        Label_Informacion_Acad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_Informacion_AcadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_Informacion_AcadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_Informacion_AcadMouseExited(evt);
            }
        });
        Panel_Informacion_Acad.add(Label_Informacion_Acad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 80));

        Panel_Izquierda_Verde.add(Panel_Informacion_Acad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        Panel_Inscripcion.setBackground(new java.awt.Color(145, 179, 59));
        Panel_Inscripcion.setPreferredSize(new java.awt.Dimension(343, 81));
        Panel_Inscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_InscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_InscripcionMouseExited(evt);
            }
        });
        Panel_Inscripcion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelInscripcion.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        labelInscripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelInscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInscripcion.setText("PROCESO DE INSCRIPCIÓN");
        labelInscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInscripcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelInscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelInscripcionMouseExited(evt);
            }
        });
        Panel_Inscripcion.add(labelInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 80));

        Panel_Izquierda_Verde.add(Panel_Inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, -1, -1));

        panel_Principal.add(Panel_Izquierda_Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ContentEstud.setBackground(new java.awt.Color(221, 221, 221));
        ContentEstud.setPreferredSize(new java.awt.Dimension(1007, 611));

        javax.swing.GroupLayout ContentEstudLayout = new javax.swing.GroupLayout(ContentEstud);
        ContentEstud.setLayout(ContentEstudLayout);
        ContentEstudLayout.setHorizontalGroup(
            ContentEstudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        ContentEstudLayout.setVerticalGroup(
            ContentEstudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        panel_Principal.add(ContentEstud, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 84, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_Principal.getAccessibleContext().setAccessibleName("");
        panel_Principal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_InscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_InscripcionMouseEntered
        // TODO add your handling code here:
        Panel_Inscripcion.setBackground(new Color(175,199,107));          
    }//GEN-LAST:event_Panel_InscripcionMouseEntered

    private void Panel_InscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_InscripcionMouseExited
        // TODO add your handling code here:
        Panel_Inscripcion.setBackground(new Color(145,179,59));   
    }//GEN-LAST:event_Panel_InscripcionMouseExited

    private void Panel_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_UsuarioMouseEntered
        // TODO add your handling code here:
        Panel_Usuario.setBackground(new Color(175,199,107));
    }//GEN-LAST:event_Panel_UsuarioMouseEntered

    private void Panel_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_UsuarioMouseExited
        // TODO add your handling code here:
        Panel_Usuario.setBackground(new Color(145,179,59));
    }//GEN-LAST:event_Panel_UsuarioMouseExited

    private void Label_Informacion_AcadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_Informacion_AcadMouseClicked
        // TODO add your handling code here:
        InformacionAcademica infoAcad = new InformacionAcademica();
        mostrarPanel(infoAcad);

    }//GEN-LAST:event_Label_Informacion_AcadMouseClicked

    private void Label_Informacion_AcadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_Informacion_AcadMouseEntered
        // TODO add your handling code here:
        Panel_Informacion_Acad.setBackground(new Color(175,199,107));        
    }//GEN-LAST:event_Label_Informacion_AcadMouseEntered

    private void Label_Informacion_AcadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_Informacion_AcadMouseExited
        // TODO add your handling code here:
        Panel_Informacion_Acad.setBackground(new Color(145,179,59));
    }//GEN-LAST:event_Label_Informacion_AcadMouseExited

    private void label_Datos_PersonalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_Datos_PersonalesMouseEntered
        // TODO add your handling code here:
        Panel_Datos_Personales.setBackground(new Color(175,199,107));        
    }//GEN-LAST:event_label_Datos_PersonalesMouseEntered

    private void label_Datos_PersonalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_Datos_PersonalesMouseExited
        // TODO add your handling code here:
        Panel_Datos_Personales.setBackground(new Color(145,179,59));        
    }//GEN-LAST:event_label_Datos_PersonalesMouseExited

    private void label_Datos_PersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_Datos_PersonalesMouseClicked
        // TODO add your handling code here:
        mostrarDatos_PersonalesEstud();

        
    }//GEN-LAST:event_label_Datos_PersonalesMouseClicked

    private void labelInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInscripcionMouseClicked
        // TODO add your handling code here:
        Inscripcion insc = new Inscripcion();
        mostrarPanel(insc);
        
    }//GEN-LAST:event_labelInscripcionMouseClicked

    private void labelInscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInscripcionMouseEntered
        // TODO add your handling code here:
        Panel_Inscripcion.setBackground(new Color(175,199,107));
    }//GEN-LAST:event_labelInscripcionMouseEntered

    private void labelInscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInscripcionMouseExited
        // TODO add your handling code here:
        Panel_Inscripcion.setBackground(new Color(145,179,59));         
    }//GEN-LAST:event_labelInscripcionMouseExited

        public static void mostrarDatos_PersonalesEstud(){
        DatosPersonalesEstudGUI datosPersonales = new DatosPersonalesEstudGUI();
        
        DatosPersonalesEstud.mostrarDatos_PersonalesEstud("Academico");
        
        datosPersonales.label_AñoIngreso.setText(DatosPersonalesEstud.AñoIngreso);
        datosPersonales.label_Cedula.setText(DatosPersonalesEstud.Cedula);
        datosPersonales.label_Correo_Institucional.setText(DatosPersonalesEstud.Correo);
        datosPersonales.label_Direccion.setText(DatosPersonalesEstud.Direccion);
        datosPersonales.label_Nombre.setText(DatosPersonalesEstud.Nombre);
        datosPersonales.label_Tel_Fijo.setText(DatosPersonalesEstud.Telefono_Fijo);
        datosPersonales.label_Tel_Movil.setText(DatosPersonalesEstud.Telefono_Movil);
        datosPersonales.label_Carrera.setText(DatosPersonalesEstud.Carrera);
        
        mostrarPanel(datosPersonales);            
            
        }
    
    
        public static void mostrarPanel(JPanel panel){

        panel.setSize(1007,1000); //Tener cuidado! debe tener el mismo tamaño del content para que esteticamente se vea bien
        panel.setLocation(0,0);
        
        ContentEstud.removeAll();
        ContentEstud.add(panel, BorderLayout.CENTER);
        ContentEstud.revalidate();
        ContentEstud.repaint();        
   
    }
    
    public static void ejecutar_pricipal(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipalEstudGUI().setVisible(true);
            }
        });
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalEstudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalEstudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalEstudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipalEstudGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipalEstudGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel ContentEstud;
    private javax.swing.JLabel Label_Escudo;
    private javax.swing.JLabel Label_Icono_Usuario;
    private javax.swing.JLabel Label_Informacion_Acad;
    private javax.swing.JLabel Label_Portal_Servicios;
    public javax.swing.JLabel Label_Usuario;
    private javax.swing.JPanel Panel_Datos_Personales;
    private javax.swing.JPanel Panel_Informacion_Acad;
    private javax.swing.JPanel Panel_Inscripcion;
    private javax.swing.JPanel Panel_Izquierda_Verde;
    private javax.swing.JPanel Panel_Superior_Gris;
    private javax.swing.JPanel Panel_Usuario;
    private javax.swing.JLabel labelInscripcion;
    private javax.swing.JLabel label_Datos_Personales;
    private javax.swing.JPanel panel_Principal;
    // End of variables declaration//GEN-END:variables
}
